namehash/ensnode

README.md, docs/V2.md, package.json, pnpm-lock.yaml, ponder.schema.ts, src/handlers/NameWrapper.ts, src/handlers/Registrar.ts, src/handlers/Registry.ts, src/lib/checkpoints.ts, src/lib/helpers.ts, src/lib/ids.ts, src/lib/subname-helpers.ts, src/lib/upserts.ts, src/plugins/eth/handlers/NameWrapper.ts, src/plugins/eth/ponder.config.ts
- implements checkpointing, but is not currently configured — it's more of a manual dev tool while ponder team speeds up historical indexing query
- i used the checkpointing feature on my end to casually verify the namewrapper logic, so i'm confident in the broad strokes of this implementation, though actually running this code on mainnet from the start will take you ~24 hours to get to the first namewrapper event
- implements namewrapper logic following plugin pattern with shared lib
- uses ensjs util for encoding label hashes
=> NameWrapper + Checkpointing

package.json
I'm not an expert in this minutiae, but creating this PR just to flag how I noticed the changes merged in https://github.com/namehash/ensnode/pull/62/files are not in full alignment with the current package.json.
Open to whatever you guys suggest.
=> Align node version

apps/ensnode/README.md
=> docs: remove superfluous next up in readme

apps/ensnode/src/handlers/Resolver.ts
=> fix: nullify empty strings in TextChanged events

apps/ensrainbow/src/ingest.ts
https://github.com/namehash/ensnode/issues/140
=> ENSRainbow: Add comments about Invalid record in ens rainbow tables

README.md, apps/ensrainbow/README.md, apps/ensrainbow/package.json, apps/ensrainbow/src/index.test.ts, apps/ensrainbow/src/index.ts, apps/ensrainbow/src/ingest.ts, apps/ensrainbow/src/utils/label-utils.test.ts, apps/ensrainbow/src/utils/label-utils.ts, apps/ensrainbow/src/utils/rainbow-record.test.ts, apps/ensrainbow/src/utils/rainbow-record.ts, package.json, pnpm-lock.yaml
For some comments from https://github.com/namehash/ensnode/pull/101
=> ENSRainbow: More fixes

apps/ensrainbow/.gitignore, apps/ensrainbow/src/index.test.ts, apps/ensrainbow/src/index.ts, apps/ensrainbow/src/ingest.ts, apps/ensrainbow/src/operations.ts, apps/ensrainbow/src/utils/label-utils.ts, apps/ensrainbow/src/utils/response-types.ts
This PR is intended to be merged into [PR 150](https://github.com/namehash/ensnode/pull/150) and offers the following enhancements to ENSRainbow.
* Refines the definition of all response types
* Applies typing more formally to how responses are built and validated
* Extracts the implementation of operations outside of API handlers
* Applies lint autoformatting
=> Refine ENSRainbow API Operations & Response Types

README.md
Applies a trivial change (linting the root README.md file) to test Vercel deploys of our docs websites.
=> lint root README.md

docs/ensnode/LICENSE, docs/ensrainbow/LICENSE
Add explicit MIT license to everything
=> Add license to docs

apps/ensnode/src/handlers/Resolver.ts, packages/ponder-schema/src/ponder.schema.ts
=> fix: return to coinTypes: .bigint.array

apps/ensrainbow/src/commands/count-command.ts, apps/ensrainbow/src/commands/ingest-command.ts, apps/ensrainbow/src/commands/server-command.ts, apps/ensrainbow/src/lib/database.ts
https://github.com/namehash/ensnode/issues/119
=> ENSRainbow: Handle interrupted ingestion

README.md, packages/ensrainbow-sdk/README.md
Closes https://github.com/namehash/ensnode/issues/122
=> Refine README content for ensrainbow-sdk

apps/ensnode/src/lib/globals.ts, pnpm-lock.yaml, pnpm-workspace.yaml
only relevant change seems to be startBlock/endBlock type related
=> deps: update ponder to 0.9.7

apps/ensnode/src/handlers/NameWrapper.ts, apps/ensnode/src/handlers/Registrar.ts, apps/ensnode/src/handlers/Registry.ts, apps/ensnode/src/lib/globals.ts, pnpm-lock.yaml, pnpm-workspace.yaml
closes #246
in debugging `Domain.name` being null I madesome minor changes to the comments & logic in those functions but at the end of the day our logic was correct and it was ponder setting `name` to null if it was `undefined` that caused the bug in the diff
=> WIP: 21M Diff Fixes

pnpm-lock.yaml, pnpm-workspace.yaml
Fixes bugs introduced in `v0.9.x` `ponder` package releases:
- https://github.com/ponder-sh/ponder/issues/1516
- https://github.com/ponder-sh/ponder/issues/1524
- https://github.com/ponder-sh/ponder/issues/1525
Related to:
- #53
=> deps(ponder): update to v0.9.14

apps/ensrainbow/package.json, package.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix(ci): update esbuild version resolution

apps/ensrainbow/src/commands/server-command.test.ts, apps/ensrainbow/src/commands/server-command.ts
=> feat(ensrainbow): enable hono cors headers for all `/v1/* routes`

pnpm-lock.yaml, pnpm-workspace.yaml
tentatively closes #280 , will re-open if that turns out to not be the case
=> deps: update to ponder 0.9.18

apps/ensrainbow/package.json, apps/ensrainbow/src/cli.test.ts, apps/ensrainbow/src/cli.ts, apps/ensrainbow/src/commands/purge-command.ts
https://github.com/namehash/ensnode/issues/253
=> ENSRainbow: Add purge command

apps/ensrainbow/Dockerfile, apps/ensrainbow/package.json, apps/ensrainbow/src/cli.test.ts, apps/ensrainbow/src/cli.ts, apps/ensrainbow/src/commands/purge-command.ts, apps/ensrainbow/src/commands/validate-command.ts, apps/ensrainbow/src/lib/database.test.ts, apps/ensrainbow/src/lib/database.ts, apps/ensrainbow/src/lib/server.ts
Close https://github.com/namehash/ensnode/issues/252
=> Add lite validation mode to ENSRainbow database validation

apps/ensrainbow/README.md, docs/ensrainbow/src/content/docs/guides/quick-start.mdx
Related to: https://github.com/namehash/ensnode/issues/239
- Added "Deploy on Railway" button for ensrainbow README
=> Added "Deploy on Railway" button for ensrainbow

pnpm-lock.yaml, pnpm-workspace.yaml
will index overnight and confirm equivalency
=> deps: ponder 0.9.20

apps/ensadmin/src/components/Layout.tsx, apps/ensadmin/src/components/PonderClient.tsx
=> fix(ensadmin): variable names

.changeset/config.json, .github/workflows/release-apps.yml, .github/workflows/release-packages.yml, apps/README.md, package.json, packages/README.md, pnpm-lock.yaml
=> feat(release): include `apps/*` changelog tracking

apps/ensrainbow/src/commands/ingest-command.ts, apps/ensrainbow/src/commands/server-command.test.ts, apps/ensrainbow/src/commands/validate-command.test.ts, apps/ensrainbow/src/lib/database.test.ts, apps/ensrainbow/src/lib/database.ts
https://github.com/namehash/ensnode/issues/332
=> ENSRainbow: change the INGESTION_UNFINISHED_KEY to become INGESTION_STATUS_KEY

.github/workflows/build_ensindexer_image.yml
Related to: https://github.com/namehash/ensnode/issues/346
=> Added workflow for ENSIndexer multi-arch Docker image build

pnpm-lock.yaml, pnpm-workspace.yaml
Includes important bugfix:
- https://github.com/ponder-sh/ponder/pull/1582
=> deps(ponder): update to v0.9.27

README.md
Limit the width of sponsor images:
=> fix(readme): image sizes

package.json, pnpm-lock.yaml
Resolves: https://github.com/namehash/ensnode/security/dependabot/11, https://github.com/namehash/ensnode/security/dependabot/12
=> fix(deps): update babel package version

.github/workflows/build_ensrainbow_v2_data_image.yml, .github/workflows/build_ensrainbow_v2_image.yml, apps/ensrainbow/Dockerfile, apps/ensrainbow/Dockerfile.data, apps/ensrainbow/download-rainbow-tables.sh, apps/ensrainbow/package.json, docs/ensnode.io/src/content/docs/ensrainbow/contributing/building.mdx, docs/ensnode.io/src/content/docs/ensrainbow/contributing/index.mdx
This commit introduces:
- GitHub Actions workflow for building ENSRainbow v2 data image
- GitHub Actions workflow for building ENSRainbow v2 application image
- Updated Dockerfile.data to support v2 data version
- Modified download-rainbow-tables.sh to handle v2 data download
- Added npm script for downloading v2 data in package.json
=> feat: add ENSRainbow v2 data and image workflows

.github/workflows/build_ensadmin_image.yml
This PR adds missing workflow that will now build and push docker image for ENSAdmin app to Github Container Registry.
=> feat(ci): include ENSAdmin docker build & push workflow

apps/ensadmin/src/app/@breadcrumbs/(apis)/gql/ponder/page.tsx, apps/ensadmin/src/app/@breadcrumbs/(apis)/gql/subgraph-compat/page.tsx, apps/ensadmin/src/app/@breadcrumbs/(apis)/layout.tsx, apps/ensadmin/src/app/layout.tsx, apps/ensadmin/src/components/app-sidebar.tsx, apps/ensadmin/src/components/connections/connection-selector.tsx, apps/ensadmin/src/components/ensadmin-icon.tsx, apps/ensadmin/src/components/ui/header.tsx
Small enhancement that addresses some of the feedback @lightwalker-eth had in #373
=> feat(ensadmin): improved breadcrumbs and sidebar links

apps/ensadmin/package.json, apps/ensadmin/src/components/connections/connection-selector.tsx, apps/ensadmin/src/components/indexing-status/components.tsx, apps/ensadmin/src/components/ui/dialog.tsx, apps/ensadmin/src/components/ui/label.tsx, pnpm-lock.yaml
I've improved the UI of adding a new connection to be inside of a Dialog component.
I also changed the `Input` to be `text` so we have more control over the validation.
A further improvement when we have React 19 would be to use some of the newer React APIs for managing form status with a server action potentially, and we can revalidate some other pages should we need to.
=> feat(ensadmin): new connection dialog

.github/workflows/build_ensindexer_image.yml, .github/workflows/deploy_ensnode.yml
Added versioning for ENSIndexer.
Version is being created on tag push.
Deployments now will also update the docker image for specific tags before redeploying.
=> Added versioning for ensindexer docker image

apps/ensadmin/src/app/@actions/live/default.tsx, apps/ensadmin/src/app/@actions/live/eth/page.tsx, apps/ensadmin/src/app/@breadcrumbs/(live)/layout.tsx, apps/ensadmin/src/app/@breadcrumbs/(live)/live/default.tsx, apps/ensadmin/src/app/@breadcrumbs/(live)/live/eth/page.tsx, apps/ensadmin/src/app/layout.tsx, apps/ensadmin/src/app/live/eth/page.tsx, apps/ensadmin/src/app/status/page.tsx, apps/ensadmin/src/components/app-sidebar.tsx, apps/ensadmin/src/components/indexing-status/components.tsx, apps/ensadmin/src/components/nav-main.tsx, apps/ensadmin/src/components/recent-registrations/components.tsx
=> feat(ensadmin): improvements to indexing status and eth registrations page

apps/ensindexer/src/lib/ponder-helpers.ts
- startBlock should default to 0 here
=> fix: default start block 0 in createStartBlockByChainIdMap

.github/workflows/switch_ensnode_environment.yml
During "switch environment" workflow run also update routing for ENSRainbow
=> Update switch wokflow to include ENSRainbow

docs/ensnode.io/config/integrations/starlight.ts
=> fix: ensnode.io Twitter image

apps/ensadmin/src/app/react-flow/AnimatedSVGEdge.tsx, apps/ensadmin/src/app/react-flow/client.tsx, apps/ensadmin/src/app/react-flow/page.tsx
I've improved `Math.sqrt()` that may produce slightly different results between environments due to floating-point precision.
Also I moved React Flow to use `next/dynamic`.
=> feat: move to dynamic import for the react-flow client

apps/ensadmin/package.json, apps/ensadmin/src/app/@actions/react-flow/page.tsx, apps/ensadmin/src/app/@breadcrumbs/react-flow/page.tsx, apps/ensadmin/src/app/react-flow/page.tsx, apps/ensadmin/src/components/ui/select.tsx, pnpm-lock.yaml
Adds a simple config to the actions area.
=> feat(ensadmin): add teaser config options

.changeset/real-lies-care.md, .github/workflows/build_ensindexer_image.yml, .github/workflows/release.yml
- E2E test for ENSIndexer changesets integration
- Moved docker image build responsibility from release workflow to per app workflow
=> Changesets versioning test

.changeset/config.json, .changeset/wicked-hornets-joke.md, .github/workflows/build_ensadmin_image.yml, .github/workflows/build_ensindexer_image.yml, .github/workflows/build_ensrainbow_image.yml
- Added versioning for non published packges
- Added versioned image build for ENSAdmin and ENSRainbow
=> Extended versioning logic

biome.json, biome.jsonc, docs/ensnode.io/package.json, package.json, packages/ens-deployments/package.json, packages/ensnode-utils/package.json, packages/ensrainbow-sdk/package.json, packages/ponder-metadata/package.json, packages/ponder-schema/package.json, packages/ponder-subgraph-api/package.json, packages/shared-configs/package.json
- disable biome for package.json
- format all package.jsons as changesets would (i.e. vscode default
=> fix: changeset linting

apps/ensindexer/src/api/index.ts, apps/ensindexer/src/lib/ponder-metadata-provider.ts, packages/ponder-subgraph-api/src/graphql.ts
something about ponder:api access too early
and graphql type
=> fix: hotfix meta

.github/workflows/release.yml, package.json
- re-enable git tags so publishing works
- remove shared-configs section from release notes and npm link
=> fix: release tags and notes

README.md, apps/ensindexer/.env.local.example, docs/ensnode.io/src/content/docs/docs/concepts/roadmap.mdx, docs/ensnode.io/src/content/docs/docs/index.mdx, docs/ensnode.io/src/content/docs/docs/usage/hosted-ensnode-instances.mdx
- update readme with 3dns check
- also adds ens-test-env ens-app-v3 check
- updates documentation regarding plugins & availability of threedns plugin
=> docs: update docs with 3dns support

docs/ensnode.io/src/components/molecules/JoinTelegram.tsx, docs/ensnode.io/src/components/organisms/InfrastructureInnovations.tsx, docs/ensnode.io/src/components/organisms/Proposal.astro
=> chore: update ensnode.io content

docs/ensnode.io/config/integrations/starlight.ts, docs/ensnode.io/src/components/atoms/icons/StarlightMagnifier.tsx, docs/ensnode.io/src/components/overrides/DocsSearch.astro, docs/ensnode.io/src/styles/globals.css
=> chore: ensnode.io search bar refinement

packages/ponder-subgraph/src/graphql.ts
from https://github.com/ponder-sh/ponder/pull/1725
=> fix: include relations fix 

.changeset/common-pianos-jog.md, apps/ensindexer/src/handlers/Registrar.ts
- hoists the invariant inline with documentation
- updated comments reflecting better understanding of context
=> fix Registrar onlyRegister patch comments

apps/ensindexer/src/handlers/Registrar.ts
these preminted names are only registered in the Registrar (hence need a Registration) but aren't registered in the Registry (hence are not yet a Domain) — this fix removes the domain creation and simply allows the skipping of the domain.update if the domain does not exist in the basenames plugin. it's much cleaner, more specific, and more accurate.
one downside of this is that the subgraph schema specifies a non-null domainId relationship. in this current patch i've kept the domainId as `node` of the preminted names, which seems alright, and results in api results like this, where the preminted names end and the normally registered names begin
the downside of this is that ponder doesn't support where filters over relationships so it's not possible to actually do a filter like
```graphql …
```
=> fix: only register preminted names

apps/ensadmin/src/components/ens-name/index.tsx, apps/ensadmin/src/components/recent-registrations/components.tsx
=> chore: minor fixes in ensadmin

apps/ensindexer/src/plugins/basenames/plugin.ts, apps/ensindexer/src/plugins/lineanames/plugin.ts, apps/ensindexer/src/plugins/subgraph/plugin.ts, apps/ensindexer/src/plugins/threedns/plugin.ts
Changes include code comments alterations requested in PR #765.
=> docs(ensindexer): update plugin code comments

.changeset/brave-foxes-sort.md, docs/ensnode.io/src/content/docs/docs/concepts/what-is-the-ens-subgraph.mdx
Closes https://github.com/namehash/ensnode/issues/877
=> Support for new ENS Subgraph version

package.json, pnpm-lock.yaml
Resolves:
- https://github.com/namehash/ensnode/security/dependabot/27
- https://github.com/namehash/ensnode/security/dependabot/28
=> fix(security): update deps to pass audit

package.json, pnpm-lock.yaml
Resolves:
- https://github.com/namehash/ensnode/security/dependabot/30
- https://github.com/namehash/ensnode/security/dependabot/31
=> deps: address security issues

apps/ensadmin/src/app/inspect/_components/render-requests-output.tsx, apps/ensadmin/src/app/status/error.tsx, apps/ensadmin/src/components/connections/connection-selector.tsx, apps/ensadmin/src/components/ui/inline-summary.tsx, apps/ensadmin/src/hooks/ensnode-connections.tsx, apps/ensindexer/test/graphnode-helpers.test.ts
- fix ensnode connect redirect
- fix connection adding race condition
- fix wrapping of status page uls
- - Correctly mock ENSRainbow client fetches so the tests pass like normal
=> Fixes for 0.34.0-rc.*

.changeset/tiny-vans-move.md, apps/ensadmin/src/components/indexing-status/backfill-status.tsx
=> Backfill status text changes

docs/ensnode.io/package.json, docs/ensrainbow.io/package.json, package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Fix to https://github.com/namehash/ensnode/security/dependabot/36
=> fix devalue vulnerability

terraform/main.tf, terraform/modules/ensindexer/main.tf, terraform/variables.tf
- ENSIndexer localhost issue fixed
- replace_unnormalized set to false for all indexer
- ENSDB size set to 250GB
- Removed 'tokenscope' plugin for alpha-sepolia
=> Render environment fixes

packages/ensnode-sdk/src/ensindexer/indexing-status/types.ts, packages/ensnode-sdk/src/shared/types.ts
Suggests refinements to https://github.com/namehash/ensnode/pull/1117
=> Refine pr 1117
