ponder.schema.ts
src/handlers/NameWrapper.ts
src/handlers/Registrar.ts
src/handlers/Registry.ts
src/handlers/Resolver.ts
src/lib/upserts.ts
src/plugins/base.eth/handlers/Registrar.ts
src/plugins/eth/handlers/Registry.ts

- first commit moves the individual imports to a module import
- from `import { domains } from "ponder:schema"` and `.insert(domains)`
- to `import schema from "ponder:schema"` and `.insert(schema.domains)`
- second comment renames the tables so
- from `.insert(schema.domains)`
- to `.insert(schema.domain)`
this makes the autogenerated api correct

singularize schema table names

---

src/handlers/Registry.ts
src/plugins/base.eth/handlers/Registrar.ts
src/plugins/linea.eth/handlers/EthRegistrar.ts

base.eth & linea.eth plugins need to make sure that the initial Transfer event emitted by a respective registar contract results in creating a new domain entity in indexer's database.

fix: ensure new domain created for initial transfer

---

src/handlers/NameWrapper.ts
src/handlers/Registrar.ts
src/lib/subname-helpers.ts

Subgraph Logic Fixes Post 21M Diff

---

src/plugins/base.eth/ponder.config.ts
src/plugins/eth/ponder.config.ts
src/plugins/linea.eth/ponder.config.ts

Defer executing the networks config object for each plugin, so that the env vars validation could become optional and only done for the activated plugins.
Resolves #37

fix(plugins): lazy-loaded config

---

.github/workflows/static-analysis.yml
src/plugins/eth/ponder.config.ts
test/helpers.spec.ts
test/plugin-helpers.spec.ts
test/subname-helpers.spec.ts

This is needed to avoid issues with ponder build process. If tests are included in the `src/` directory, ponder won't be able to start indexing:
Also, this PR drops the end block limit on the `eth` plugin and adds new check to static analysis task on CI.

fix(ponder-build): move tests out the `src/` dir

---

packages/ponder-schema/src/ponder.schema.ts

adds index on `(parent_id, id)` for each type of event. the diff is more verbose than it perhaps needed to be but that's the only change here

fix: add indexes to events for speedier reference lookups

---

packages/ponder-subgraph-api/src/graphql.ts

self explanatory, fixes an issue tracked in #79

fix: default to 100 for plurals without limit specified

---

apps/ensnode/src/handlers/Resolver.ts

fixes #39 
i naively called `upsertAccount` for account values in MulticoinAddrChanged events, but that is both incorrect and unnecessary.
note the lack of Account access in this handler: https://github.com/ensdomains/ens-subgraph/blob/c8447914e8743671fb4b20cffe5a0a97020b3cee/src/resolver.ts#L59

fix: dont upsertAccount for multicoin address newAddress

---

.github/workflows/ci.yml

This one allows saving a lot of space on the GitHub Action runtime and avoid "no space left on the device" error. Before this change, there would be separate steps for building Docker image, and for pushing it to container registry. It would require a temp file to be saved and shared between those files. This temp file was too large to fit on the available storage space.
Error:
- https://github.com/namehash/ensnode/actions/runs/13061577337/job/36445589428#step:3:316

fix(ci): merge docker build & push

---

apps/ensnode/src/handlers/NameWrapper.ts
packages/ensnode-utils/src/subname-helpers.spec.ts
packages/ensnode-utils/src/subname-helpers.ts

this fixes one of the issues in #79 regarding `WrappedDomain.name` being null — my original re-implementation of the dns packet decoding helper was subtly incorrect. this version goes line-by-line and mirrors the subgraph implementation more closely. i've included a test case to verify against the specific instance that surfaced this issue.
https://github.com/ensdomains/ens-subgraph/blob/master/src/nameWrapper.ts#L30

fix: correctly implement dns packet decoding from subgraph

---

packages/ponder-schema/src/ponder.schema.ts

closes #126 
giving the index a unique name meant that drizzle only applied the index to the first table that used the helper — letting drizzle autogenerate the idnex name ensures that each table gets a composite index

fix: remove event index name

---

apps/ensnode/src/handlers/Resolver.ts
packages/ponder-schema/src/ponder.schema.ts

this provides incorrect graphql typings but correct graphql responses (since bigints are represented as string in json anyway). so it's effectively subgraph compatible. when the bugs are fixed we can revert to correct behavior

fix: temporarily store coinTypes as string array to avoid parsing bugs

---

apps/ensnode/src/handlers/Resolver.ts

probably some merge conflict when we wrapped `makeResolverHandlers` but the bugfix in #105 got overwritten so this is that again

fix: stop upserting addresses in multicoinaddresschanged

---

apps/ensrainbow/package.json
apps/ensrainbow/src/count-keys.ts
apps/ensrainbow/src/index.test.ts
apps/ensrainbow/src/index.ts
apps/ensrainbow/src/ingest.ts
apps/ensrainbow/src/operations.ts
apps/ensrainbow/src/utils/byte-utils.ts
apps/ensrainbow/src/utils/constants.ts
apps/ensrainbow/src/utils/label-utils.test.ts
apps/ensrainbow/src/utils/label-utils.ts
apps/ensrainbow/src/utils/rainbow-record.test.ts
apps/ensrainbow/src/utils/rainbow-record.ts
apps/ensrainbow/tsconfig.json
pnpm-lock.yaml

This PR aims to fix the issue that causes Docker to fail image build process for ENSRainbow codebase.
Feel free to review commit by commit.
Key changes:
- update TS config file to target Node.js runtime (resolves docker build error),
- link to `ensnode-utils` package via pnpm workspace (resolves #154),
- replace ts-expect-error with type-casting to allow testing invalid inputs (resolves #155).
Other changes:
- include ENSRainbow in static analysis CI checks (enables more checks on CI for ENSRainbow).
Example failed CI run: https://github.com/namehash/ensnode/actions/runs/13103011295/job/36553617832#step:3:273
<details isOpen="false">
<summary>Error log</summary>
```
#26 [ingestor 3/3] RUN node dist/ingest.js
#26 0.151 node:internal/modules/cjs/loader:1228
#26 0.151   throw err;
#26 0.151 …
```

fix(ensrainbow): TS output path during Docker build

---

packages/ponder-schema/src/ponder.schema.ts

a workaround for the malformed `//U_W_U\\` text key identified in #79 
the issue is being tracked with ponder team in https://github.com/ponder-sh/ponder/issues/1484 but this workaround is acceptable for now. it produces the incorrect graphql type, similar to the bigint array stopgap, but the json data response itself continues to be subgraph-compatible

fix: use jsonb for texts to fix malformed string serialization bug

---

.dockerignore
apps/ensrainbow/.dockerignore
apps/ensrainbow/Dockerfile
apps/ensrainbow/Dockerfile.data

- ignore host artifacts so builds will work even if user has these files on local machine (also helps with out of space issues)
- no need to copy node modules from app-deps if we're inheriting from app-deps stage
- and there's no build step so the efficiency of splitting into multiple stages any only copying over deps + built app isn't important, we can just inherit from the deps stage directly.
- simplifies ingest significantly now that we're manually building

fix: streamling dockerfiles further

---

pnpm-lock.yaml
pnpm-workspace.yaml

Ponder `v0.9.17` includes fixes for important bugs:
- https://github.com/ponder-sh/ponder/issues/1513
- https://github.com/ponder-sh/ponder/issues/1532
- https://github.com/ponder-sh/ponder/issues/1535

deps(ponder): update to v0.9.17

---

.changeset/config.json
biome.json
package.json
pnpm-lock.yaml

This PR turns the prettier code formatter off. Aiming to prevent JSON files from being formatted with other rules than our primary code formatting tool, Biome, expects.
Here's a PR created by changesets that breaks the code style rules:
- https://github.com/namehash/ensnode/pull/287/files#diff-06ad7b96e159b0f2fc92bd85eb0acb529de706932cf64b682deea992baf059b2
Changesets released a new CLI version that allows turning `prettier` tool off:
- https://github.com/changesets/changesets/pull/1588

fix(changesets): disable auto-formatting

---

.changeset/config.json
biome.json
package.json
pnpm-lock.yaml

Reverts namehash/ensnode#288 due to a bug in changesets:
- https://github.com/changesets/changesets/issues/1593
We'll be able to disable auto-formatting once either of the following PRs is released:
- https://github.com/changesets/changesets/pull/1590
- https://github.com/changesets/changesets/pull/1594

revert(changesets): disable auto-formatting

---

packages/ponder-schema/src/ponder.schema.ts

speeds up queries that access things like `domain { registrant { id } }` etc
please read this diff with "hide whitespace" on

fix: add indexes for reverse domainId relations

---

apps/ensadmin/Dockerfile
apps/ensindexer/Dockerfile

This allows using `--frozen-lockfile` option when installing dependencies for which lockfile was generated with specifying pnpm version.
Related to:
- #315

fix(apps): use pnpm version arg with every app

---

pnpm-lock.yaml
pnpm-workspace.yaml

This PR includes Ponder dependency upgrade which includes:
- https://github.com/ponder-sh/ponder/pull/1580
that IMO fixes:
- https://github.com/ponder-sh/ponder/issues/1577

deps(ponder): update to v0.9.26

---

package.json
pnpm-lock.yaml

This PR fixes duplicated overrides in NPM file that were causing duplicated entries in PNPM lockfile, resulting in failed `pnpm install --frozen-lockfile` command.

fix(deps): dedupe dependency overrides

---

docs/ensrainbow/package.json
docs/ensrainbow/src/components/organisms/AboutRainbowSections.tsx
docs/ensrainbow/src/components/organisms/Footer.tsx
docs/ensrainbow/src/components/organisms/ForDevelopers.tsx
docs/ensrainbow/src/components/organisms/FullRainbow.tsx
docs/ensrainbow/src/components/organisms/Header.tsx
docs/ensrainbow/src/components/organisms/Hero.tsx
pnpm-lock.yaml

Fixes and changes to ENSRainbow LP, including:

chore: ENSRainbow - landing page fixes - 1st batch

---

apps/ensindexer/src/handlers/Registrar.ts
apps/ensindexer/src/handlers/Resolver.ts
apps/ensindexer/src/plugins/base/handlers/Registrar.ts
apps/ensindexer/src/plugins/eth/handlers/EthRegistrar.ts
apps/ensindexer/src/plugins/linea/handlers/EthRegistrar.ts

fix: correctly parse args where null bytes values may be encountered

---

apps/ensadmin/package.json
docs/ensrainbow/package.json

This PR is a fix to situation where changesets attempt to publish to NPM from `docs` website package. For example:
- https://github.com/namehash/ensnode/actions/runs/13908403750

fix(ci): prevent `docs` from being published to npm

---

apps/ensadmin/next.config.ts

This PR provide backward compatibility for ENSNode services. The older ones would redirect their homepage to ENSAdmin `/about` which was discontinued in the application router.
Feel free to test out the redirect from ENSAdmin `/about` to ENSAdmin `/` (which ENSAdmin app internally resolves to `/status`)
- https://adminensnodeio-git-fix-ensadmin-about-redirect-namehash.vercel.app/about?ensnode=https%3A%2F%2Fapi.mainnet.green.ensnode.io%2F

fix(ensadmin): set `/about` path redirect

---

apps/ensrainbow/.env.local.example
docker-compose.yml
docs/ensnode.io/src/content/docs/ensnode/contributing/index.mdx
docs/ensnode.io/src/content/docs/ensrainbow/contributing/building.mdx
examples/example-docker-compose/docker-compose.yml
package.json

This PR:
1. Allows selectively building local docker images from source code, ie. by running any of the following commands
- `pnpm docker:build:ensadmin` 
- `pnpm docker:build:ensindexer` 
- `pnpm docker:build:ensrainbow`
- `pnpm docker:build:ensnode`
2. Enables auto-pulling docker images from ghcr.io registry that were not found locally. This way, a user can run all services just with the following command:
- `docker compose up -d`
3. Aligns docker compose example file (`examples/example-docker-compose/docker-compose.yml`) with the root docker compose file (`docker-compose.yml`). Uses only the `latest` tag for service images.

fix(docker): include `ghcr.io` in image names

---

apps/ensindexer/src/lib/ponder-helpers.ts

This PR allows `0` to be a valid start block for a chain. The Anvil network starts at block `0` and we need to handle it well.

fix(ensindexer): update validation logic

---

.dockerignore
apps/ensadmin/.env.local.example
apps/ensadmin/package.json
apps/ensadmin/src/app/layout.tsx
apps/ensadmin/src/lib/env.ts
docker-compose.yml
examples/example-docker-compose/docker-compose.yml
pnpm-lock.yaml

This is a follow up PR to:
- https://github.com/namehash/ensnode/pull/398
This PR support reading env vars during runtime, and avoid doing so during build time. It also allows leveraging Vercel defaults for setting `metadataBase` URL to a correct deployment URL. For other platforms, setting `ENSADMIN_PUBLIC_URL` should be done instead.
Also, resolves:
- https://github.com/namehash/ensnode/security/dependabot/13
- https://github.com/namehash/ensnode/security/dependabot/14

fix(ensadmin): use dynamic metadata

---

apps/ensadmin/.env.local.example
apps/ensadmin/Dockerfile
apps/ensadmin/README.md
apps/ensadmin/src/app/@actions/gql/ponder/page.tsx
apps/ensadmin/src/app/@actions/gql/subgraph-compat/page.tsx
apps/ensadmin/src/app/gql/ponder/page.tsx
apps/ensadmin/src/app/gql/subgraph-compat/page.tsx
apps/ensadmin/src/app/ponder-client-api/page.tsx
apps/ensadmin/src/components/connections/connection-selector.tsx
apps/ensadmin/src/components/connections/ensnode-url-validator.ts
apps/ensadmin/src/components/connections/use-connections.ts
apps/ensadmin/src/components/ensnode/hooks.ts
apps/ensadmin/src/components/recent-registrations/hooks.ts
apps/ensadmin/src/lib/env.ts
docker-compose.yml
docs/ensnode.io/src/content/docs/index.mdx
examples/example-docker-compose/docker-compose.yml

This PR adds a CTA that links to ENSAdmin.
But also, this PR updates:
- The way we define default ENSNode instance URLs. 
- It was a single URL
- It's a list of URLs from now on
- The way we call ENSNode instance URLs in application config
- It used to be _preferred_ URL
- Now it's _default_ URL

docs(ensnode): include `Try it Now` CTA

---

apps/ensadmin/package.json
docs/ensnode.io/src/pages/index.astro
pnpm-lock.yaml

This PR reverts the look and feel of ENSNode landing page prior to changes made in:
- https://github.com/namehash/ensnode/pull/415
Also, the PR addresses deps audit issue reported here:
- https://github.com/namehash/ensnode/security/dependabot/16

revert(ensnode.io): vanilla LP look and feel

---

packages/ponder-schema/src/ponder.schema.ts

closes https://github.com/namehash/ensnode/issues/174
ponder always `snake_case`s column names, so specifying them is unnecessary. i confirmed schema definition equivalence with `pg_dump "postgresql://..." -n public --schema-only > local.sql` between main and this PR and they're identical, so the generate table names are the same

chore: remove manual snake_case of column names, unnecessary

---

apps/ensindexer/ponder.config.ts
apps/ensindexer/src/lib/plugin-helpers.ts

there was no bug caused by this behavior but it bothered me that we weren't actually awaiting the registration of the handlers before passing control back to ponder — so this makes sure that every ponder.on handler is registered before returning the config to ponder

fix: await handler activation

---

packages/ponder-subgraph-api/src/graphql.ts

- removing the manual snake_case accidentally broke an internal assumption in the subgraph compatible api

fix: snake_case db column names for intersection tables

---

CONTRIBUTING.md
README.md
docs/ensnode.io/config/integrations/starlight.ts
docs/ensnode.io/src/components/molecules/TelegramInvite.astro
docs/ensnode.io/src/components/overrides/TableOfContents.astro
docs/ensnode.io/src/styles/globals.css

Closes #510 
Another idea (in addition to those marked in 510) is to promote the group on the docs sidebar like below:
Wording to be changed of course, just wanted to demonstrate the idea!

feat(ensnode.io/docs): promote telegram group

---

.github/workflows/deploy_ensnode.yml

PR fixing Railway deployment workflow. Currently it always overrides target env to green. After the fix, it'll read the target env from job's input.

Remove hardcoded env

---

apps/ensindexer/src/api/index.ts
apps/ensindexer/src/lib/ponder-helpers.ts
apps/ensindexer/src/lib/ponder-metadata-provider.ts
packages/ponder-metadata/package.json
packages/ponder-metadata/src/index.ts
packages/ponder-metadata/src/prometheus-metrics.test.ts
packages/ponder-subgraph-api/package.json
packages/ponder-subgraph-api/src/graphql.ts
packages/ponder-subgraph-api/src/index.ts
packages/ponder-subgraph-api/src/middleware.ts
packages/ponder-subgraph-api/src/types.ts
pnpm-lock.yaml

This PR introduces a data provider interface for `ponder-subgraph-api` package. With this change, it's the application's (i.e. ENSIndexer's) responsibility to provide async methods to fetch current data for Subgraph's `_meta` field. This data includes :
- the last indexed block info (deriver from Ponder status DB table and RPC request),
- Ponder build ID (derived from Ponder metadata DB table),
- if there were any indexing errors (derived from Ponder metrics).
With these changes, the `ponder-subgraph-api` package does not a direct dependency on the `ponder-metadata` packages. They are integrated on the ENSIndexer application level.
Also, `_meta` field can now be built for all supported ENS Deployments: `mainnet`, `sepolia`, `holesky`, and `ens-test-env`.

feat(subgraph): _meta resolver data provider

---

.github/workflows/create_github_release.yml
.github/workflows/release.yml
.github/workflows/test_ci.yml
apps/ensindexer/src/plugins/README.md

This PR makes Changesets to not create a Github Release and instead, has a separate Github Action to read the changesets-made PR and create the new Github Release from its description.
Also, this PR updates `ACTIVE_PLUGINS` values to match recent refactorings.

feat(ci): update github release workflow

---

.changeset/two-ways-shout.md
.github/workflows/release.yml

This PR fixes an error where our CI workflow job cannot access pull request details in order to generate release notes. The job needs to include github token in order to use `gh` command from Github CLI.
Related:
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-github-cli-in-workflows
Failed CI job:
- https://github.com/namehash/ensnode/actions/runs/14516776624/job/40730436088

fix(ci): allow github release action to read PR details

---

CONTRIBUTING.md
apps/ensindexer/README.md
examples/example-docker-compose/README.md

Three links weren't updated when the docs folder got renamed. This fixes that.

docs: fix outdated links

---

.changeset/cold-owls-hug.md
.changeset/config.json
.github/workflows/release.yml
package.json

This PR makes:
- changesets not to publish git tags for any packages
- formats release notes
- drops initial paragraph and header
- includes links to NPM packages published with the current release
- includes links to Docker images published with the current release

fix(github-release): release notes format

---

.github/workflows/release.yml

more correct, less confusing. workflow is `release`, contains 3 jobs, `changesets`, `build-and-push-ensnode`, `create-github-release`

fix: change release job name to changesets

---

.changeset/famous-views-guess.md

A PR triggering patch release in order to test the Github Release Notes correctess.

docs(changeset): Ensuring Github Release Notes correctness: NPM links

---

apps/ensadmin/package.json
apps/ensadmin/src/components/connections/connection-selector.tsx
apps/ensadmin/src/components/nav-main.tsx
pnpm-lock.yaml

Closes #633 
Screenshots for permuations:
The whole row was clickable before, which worked but it wasn't correct since there was a <button> with another <button> inside. This PR updates that to now have the DropdownMenuItem button, and additional delete/copy buttons:

feat: improved connection library

---

apps/ensadmin/src/app/inspector/page.tsx

This always shows the `teaser` badge on the inspector page but still hides it in the breadcrumbs. A separate fix is needed for that so we can better stack those items for mobile.

fix(ensadmin): always show teaser badge on inspector page

---

.changeset/fast-badgers-trade.md
apps/ensindexer/ponder.config.ts
apps/ensindexer/src/lib/plugin-helpers.ts
apps/ensindexer/src/lib/ponder-helpers.ts
apps/ensindexer/test/ponder-helpers.test.ts

panics if there are no custom rpc endpoints defined for the networks that the config ends up using and provides verbose error message

fix: allow rpc endpoints to be undefined at runtime and checked at config gen time

---

.changeset/blue-kings-flash.md
apps/ensindexer/src/handlers/Registry.ts
apps/ensindexer/src/handlers/Resolver.ts
apps/ensindexer/src/handlers/ThreeDNSToken.ts
apps/ensindexer/src/lib/ids.ts
apps/ensindexer/test/ids.test.ts

closes https://github.com/namehash/ensnode/issues/682

feat: chain-scope resolver ids for non-subgraph plugins

---

.changeset/little-cycles-deny.md
apps/ensindexer/src/handlers/Resolver.ts
apps/ensindexer/src/lib/lib-helpers.ts
apps/ensindexer/test/lib-helpers.test.ts

closes https://github.com/namehash/ensnode/issues/718

fix: strip null bytes from text changed events

---

apps/ensindexer/src/handlers/NameWrapper.ts
apps/ensindexer/src/handlers/Registrar.ts
apps/ensindexer/src/handlers/Registry.ts
apps/ensindexer/src/handlers/Resolver.ts
apps/ensindexer/src/handlers/ThreeDNSToken.ts
apps/ensindexer/src/lib/dns-helpers.ts
apps/ensindexer/src/plugins/basenames/handlers/Registrar.ts
apps/ensindexer/src/plugins/lineanames/handlers/Registrar.ts
apps/ensindexer/src/plugins/subgraph/handlers/Registrar.ts
apps/ensindexer/src/plugins/subgraph/handlers/Registry.ts
apps/ensindexer/test/dns-helpers.test.ts
packages/ensnode-utils/package.json
packages/ensnode-utils/src/index.ts
packages/ensnode-utils/src/subname-helpers.test.ts
packages/ensnode-utils/src/subname-helpers.ts
packages/ensnode-utils/tsup.config.ts

closes #41 
i don't think these helpers need to be in ensnode/utils, especially because we were having trouble with the Buffer typings, since ensnode utils specifies browser libs and whatnot. so for simplicity and the tightness of the ensnode/utils lib, i've removed the dnspacketbytes lib and just exported all of the subname helpers from the root index — it's much cleaner now and especially on the consumer end where all imports come from `@ensnode/utils` rather than some some `@ensnode/utils/subname-helpers`
no changeset necessary, imo

fix: move dnsPacketBytes to dns-helpers and document

---

apps/ensindexer/src/handlers/NameWrapper.ts

closes https://github.com/namehash/ensnode/issues/534
adds discussion for why that value is used in NameWrapper
changeset not necessary for internal comments

docs: add comments about NameWrapper's usage of registrar managed name

---

pnpm-lock.yaml
pnpm-workspace.yaml

Includes cached `debug_traceCall` RPC call method released with:
- https://github.com/ponder-sh/ponder/pull/1767
Only `ponder` dependency got a version bump, as the rest of `@ponder/*` packages with version `0.10.26` do not include any code updates (it's just version bumps after looking at changelogs of those packages) and the version `0.10.28` was not released for these.

deps(ponder): update to v0.10.28

---

.changeset/hip-melons-arrive.md
.github/workflows/test_ci.yml
packages/ens-deployments/package.json
packages/ensnode-sdk/package.json

Solves an issue where secret value would not be provided when running the workflow for a branch from forked repo.
Example failed workflow run:
https://github.com/namehash/ensnode/actions/runs/15565570790/job/43843278971
Also, this PR fixes references across monorepo dependencies:
```
 WARN  Issues with peer dependencies found
.
├─┬ @ensnode/ensrainbow-sdk 0.27.0
│ └── ✕ missing peer viem@^2.22.13
└─┬ @ensnode/utils 0.27.0
└── ✕ missing peer viem@^catalog:
✕ Conflicting peer dependencies:
viem  
```
The PR replaces PNPM `catalog` references, as these were not always properly resolved during package build process. Example for `^catalog:` reference not being replace, while all `catalog:` references were replaced correctly for this particular `package.json` file: …

fix(ci): use inline values for the `test-ci` workflow

---

docs/ensnode.io/src/content/docs/docs/concepts/what-is-ensnode.mdx
docs/ensnode.io/src/content/docs/docs/concepts/what-is-the-ens-subgraph.mdx
docs/ensnode.io/src/styles/starlight.css

The previous PR made way to actually improve the bullet styles the way we want them. The styles now look much better across the docs:

improved bullet styles for docs

---

.changeset/icy-clubs-shave.md
apps/ensadmin/src/components/indexing-status/view-models.test.ts
apps/ensindexer/src/config/config.schema.ts
apps/ensindexer/src/config/types.ts
apps/ensindexer/src/lib/lib-config.ts
apps/ensindexer/src/lib/plugin-helpers.ts
apps/ensindexer/src/plugins/basenames/lib/registrar-helpers.ts
apps/ensindexer/src/plugins/lineanames/lib/registrar-helpers.ts
apps/ensindexer/test/dns-helpers.test.ts
packages/datasources/src/lib/types.ts

This reverts changes from PR #804

Revert "refactor(datasources): define ENSNamespaceId enum"

---

.github/scripts/promote_ensadmin.sh
.github/workflows/deploy_switch_ensnode_environment.yml

closes #799
ensures that the production ENSAdmin deployment is the exact sha of associated release when switching active env
this does mean that changes to ENSAdmin that are pushed to main are **NOT** automatically deployed to production, and any execution of the "switch active environment" gh action will **reset** the ENSAdmin production deployment to whatever it was when the release was cut.
if we want to run a more recent version of ENSAdmin against a same-versioned but not-same-commit instance of ENSNode, we need to manually promote the correct deployment in vercel. not the end of the world.

feat: add ensadmin version locking to env switching script

---

.changeset/tricky-keys-design.md
apps/ensadmin/src/components/ensnode/hooks.ts
apps/ensadmin/src/components/ensnode/types.ts
apps/ensadmin/src/components/indexing-status/components.tsx
apps/ensadmin/src/components/indexing-status/utils.ts
apps/ensadmin/src/components/indexing-status/view-models.test.ts
apps/ensadmin/src/components/indexing-status/view-models.ts
apps/ensadmin/src/components/recent-registrations/components.tsx
docs/ensnode.io/src/content/docs/docs/deploying/terraform.mdx
packages/ponder-metadata/src/index.ts
packages/ponder-metadata/src/middleware.ts
packages/ponder-metadata/src/types/common.ts

Replace `network` with `chain`, and `networks` with `chains`. This change aligns well with updates introduced in Ponder 0.11 version.
Related to #818

refactor: update terminology

---

.changeset/thirty-parents-yawn.md
apps/ensrainbow/Dockerfile
pnpm-lock.yaml

Reduce size of the image from 1.5GB to 0.5GB. Now only `ensrainbow` app is copied and installed. The difference comes from `pnpm install command` 1.32GB to 0.29GB.
Closes https://github.com/namehash/ensnode/issues/862

Reduce size of the ENSRainbow docker image

---

terraform/modules/ensindexer/main.tf

ENSIndexer service is hosted on port `10000` when it comes to render.com platform.

fix(cicd): render service port

---

pnpm-lock.yaml
pnpm-workspace.yaml

Change aiming to fix [the dependabot warning](https://github.com/namehash/ensnode/security/dependabot/40) about this [Hono vulnerability issue](https://github.com/advisories/GHSA-92vj-g62v-jqhh)
Per [Hono's release notes since our last version (4.7.6)](https://github.com/honojs/hono/releases), there shouldn't be any breaking changes, but since it affects a large number of our apps, and the version bump is quite significant, I'd appreciate it if any of you could confirm that all works well with that fix.
UPDATE: here is the [diff between our previously used version and the newest bump](https://github.com/honojs/hono/compare/v4.7.6...v4.9.7). I didn't check it fully. Only had a look at the release notes.

fix: Bump Hono version to 4.9.7

---

.changeset/seven-peas-look.md
apps/ensindexer/src/config/config.schema.ts
apps/ensindexer/src/config/derived-params.ts
apps/ensindexer/src/config/environment-defaults.ts
apps/ensindexer/src/config/index.ts
apps/ensindexer/src/config/types.ts
apps/ensindexer/src/lib/lib-config.ts
apps/ensindexer/test/config.test.ts
apps/ensindexer/test/environment-defaults.test.ts
apps/ensindexer/test/utils/mockConfig.ts
packages/ensnode-sdk/src/ensindexer/config/types.ts
packages/ensnode-sdk/src/ensindexer/config/zod-schemas.ts

closes https://github.com/namehash/ensnode/issues/1104
`SUBGRAPH_COMPAT` is now user-configurable, reflected in the internal docs

Introduce SUBGRAPH_COMPAT behavior

---

packages/ensnode-schema/src/subgraph.schema.ts

- `error: index row requires 23456 bytes, maximum size is 8191` likely caused by domain.name and/or labelName 
- renamed `idx` to `byDomainId` to match new pattern
- removed irrelevant index on subdomain count

hotfix: remove indexes on text columns

---

apps/ensindexer/src/api/lib/indexing-status/ponder-metadata/config.ts
apps/ensindexer/test/ponder-metadata.test.ts

This PR is fixing a regression issue introduced with PR #1133. The issue was about setting default `startBlock` to `0` for a ponder config datasource. The correct action would be to simply skip such value and move on.
This PR stops using default values for startBlock and endBlock. Those are skipped if undefined for a ponder datasource (accounts, chains, contracts).

fix(ensindexer): ponder config parsing
